sudo: required

language: node_js

node_js:
  - "10"

services:
  - docker

before_install:
  - cd scraper && npm install
  - cd ../api && npm install
  - cd ../ docker-compose up --build test

script:
  - docker-compose run --rm test npm test
